const {pool}=require('../config/db'); const Booking=require('../models/bookingModel'); const Passenger=require('../models/passengerModel'); const generatePnr=require('../utils/generatePnr'); const notify=require('./notificationService');
exports.create=async(user,data)=>{const c=await pool.getConnection();try{await c.beginTransaction(); const [flights]=await c.execute("SELECT * FROM flights WHERE id=? AND status IN ('scheduled','delayed') AND departure_time>NOW() FOR UPDATE",[data.flight_id]);if(!flights[0]){const e=new Error('Flight is not available');e.statusCode=409;throw e}
 const seatIds=data.passengers.map(p=>Number(p.seat_id));if(new Set(seatIds).size!==seatIds.length){const e=new Error('Every passenger must have a different seat');e.statusCode=422;throw e} const marks=seatIds.map(()=>'?').join(','); const [seats]=await c.execute(`SELECT * FROM seats WHERE flight_id=? AND id IN (${marks}) AND is_available=1 FOR UPDATE`,[data.flight_id,...seatIds]);if(seats.length!==seatIds.length){const e=new Error('One or more selected seats are unavailable');e.statusCode=409;throw e}
 const seatMap=new Map(seats.map(s=>[Number(s.id),s]));const total=seats.reduce((sum,s)=>sum+Number(flights[0].base_price)+Number(s.price_modifier),0);let pnr;for(let i=0;i<5;i++){pnr=generatePnr();const [x]=await c.execute('SELECT id FROM bookings WHERE pnr=?',[pnr]);if(!x.length)break}
 const [result]=await c.execute('INSERT INTO bookings(pnr,user_id,flight_id,contact_email,contact_phone,total_amount) VALUES(?,?,?,?,?,?)',[pnr,user.id,data.flight_id,data.contact_email,data.contact_phone,total]);
 for(const p of data.passengers){if(!seatMap.has(Number(p.seat_id)))throw new Error('Invalid seat');await c.execute('INSERT INTO passengers(booking_id,seat_id,first_name,last_name,gender,date_of_birth,passport_number,nationality) VALUES(?,?,?,?,?,?,?,?)',[result.insertId,p.seat_id,p.first_name,p.last_name,p.gender,p.date_of_birth,p.passport_number||null,p.nationality||null]);}
 await c.execute(`UPDATE seats SET is_available=0 WHERE id IN (${marks})`,seatIds);await c.commit();await notify.send(user.id,'Booking created',`Booking ${pnr} is awaiting payment.`,'booking');return exports.details(result.insertId,user);
 }catch(e){await c.rollback();throw e}finally{c.release()}};
exports.details=async(id,user)=>{const b=await Booking.findById(id);if(!b||(user.role!=='admin'&&Number(b.user_id)!==Number(user.id))){const e=new Error('Booking not found');e.statusCode=404;throw e}return {...b,passengers:await Passenger.findByBooking(id)};};
exports.cancel=async(id,user)=>{const b=await exports.details(id,user);if(!['pending','confirmed'].includes(b.status)){const e=new Error('This booking cannot be cancelled');e.statusCode=409;throw e}const c=await pool.getConnection();try{await c.beginTransaction();await c.execute("UPDATE bookings SET status='cancelled' WHERE id=?",[id]);await c.execute('UPDATE seats s JOIN passengers p ON p.seat_id=s.id SET s.is_available=1 WHERE p.booking_id=?',[id]);await c.commit();await notify.send(b.user_id,'Booking cancelled',`Booking ${b.pnr} has been cancelled.`,'booking');return Booking.findById(id)}catch(e){await c.rollback();throw e}finally{c.release()}};
